library(devtools)
create_package("D:/Francesca/pcir")

library(usethis)
use_package("dplyr")
use_package("tidyr")
use_package("ggplot2")
use_package("Hmisc")

# Set the directory for saving R scripts
r_directory <- file.path("D:/Francesca/pcir", "R")

# Ensure the R directory exists
if (!dir.exists(r_directory)) {
  dir.create(r_directory)
}

# Define and save the counting function
counting_code <- "
#' Create a Count Table with Percentages, Mean, and SD
#'
#' This function takes a data frame, transforms it by computing counts, percentages,
#' mean, and standard deviation for specified columns. It helps in summarizing
#' the data to understand the distribution and variation.
#'
#' @param df1 A data frame containing the data to be processed. The data frame
#' should have at least 5 columns to select from.
#' @return A data frame with computed statistics, including counts, percentages,
#' mean, and standard deviation.
#' @examples
#' df1 <- data.frame(A = c(-1, 2, 2, 3, -1), B = c(-1, 2, 3, -1, 2),
#' C = c(1, 2, -2, 3, -1), D = c(3, 2, 1, -1, -2), E = c(2, 3, 1, -1, -3))
#' result <- counting(df1)
#' print(result)
#' @export
counting <- function(df1) {
  df1 %>%
    select(2:6) %>%
    pivot_longer(everything()) %>%
    group_by(name, value) %>%
    summarise(Count = n()) %>%
    group_by(name) %>%
    mutate(`%` = 100 * (Count / sum(Count)),
           Mean = weighted.mean(value, Count),
           SD = sqrt(Hmisc::wtd.var(value, Count)),
           Total = sum(Count)) %>%
    ungroup() %>%
    pivot_wider(names_from = 'value',
                names_sep = ' ',
                values_from = c('Count', '%'),
                names_vary = 'slowest')
}
"
writeLines(counting_code, file.path(r_directory, "counting.R"))

# Define and save the pci function
pci_code <- "
#' Calculate the Potential for Conflict Index (PCI)
#'
#' This function calculates the Potential for Conflict Index (PCI) based on the
#' counts provided. PCI is useful in understanding the level of consensus and
#' conflict in the data.
#'
#' @param df2 A data frame generated by the `counting` function, containing the
#' counts and related statistics.
#' @return A data frame with the calculated PCI values for each group.
#' @examples
#' df2 <- counting(df1)
#' pci_values <- pci(df2)
#' print(pci_values)
#' @export
pci <- function(df2) {
  df2$nu <- 1 * df2$`Count -1`
  df2$na <- 1 * df2$`Count 1`
  df2$xt <- df2$nu + df2$na
  df2$z <- 1 * df2$Total
  df2$PCI <-  (1 - (df2$na / df2$xt - df2$nu / df2$xt)) * df2$xt / df2$z
  df2 <- df2 %>%
    mutate_if(is.numeric, round, digits = 2)
  return(df2)
}
"
writeLines(pci_code, file.path(r_directory, "pci.R"))

# Define and save the bubble function
bubble_code <- "
#' Create a Bubble Plot for PCI Visualization
#'
#' This function generates a bubble plot to visualize the results of the PCI
#' calculation. It shows the mean action acceptability on the y-axis and the PCI
#' value as the size of the bubbles.
#'
#' @param df3 A data frame generated by the `pci` function, containing the PCI
#' values and other statistics.
#' @return A ggplot2 object representing the bubble plot.
#' @examples
#' df3 <- pci(df2)
#' p <- bubble(df3)
#' print(p)
#' @export
bubble <- function(df3) {
  ggplot(df3, aes(x = name, y = Mean, size = PCI)) +
    geom_hline(yintercept = 0, colour = 'black') +
    geom_point(color = 'gray', show.legend = TRUE) +
    geom_text(aes(label = after_stat(df3$PCI)),
              nudge_y = 0.35, nudge_x = 0.1, size = 5) +
    ylab('Action acceptability') + xlab('') +
    ylim(-1, 1) +
    scale_size_area(max_size = 14) +
    theme_minimal() +
    theme(panel.grid.major.y = element_blank(),
          panel.grid.minor.y = element_blank(),
          panel.grid.major.x = element_blank(),
          panel.grid.minor.x = element_blank(),
          axis.title.x = element_text(size = 16),
          axis.title.y = element_text(size = 16),
          axis.text.x = element_text(size = 14, angle = 45, vjust = 1, hjust = 1),
          axis.text.y = element_text(size = 14),
          axis.line.x = element_line(colour = 'white'),
          axis.line.y = element_line(colour = 'black'),
          axis.ticks = element_line(colour = 'black'),
          legend.key.size = unit(1, 'cm'),
          legend.key.height = unit(1, 'cm'),
          legend.key.width = unit(1, 'cm'),
          legend.title = element_text(size = 16),
          legend.text = element_text(size = 14))
}
"
writeLines(bubble_code, file.path(r_directory, "bubble.R"))

# Since the package structure already exists, no need to recreate DESCRIPTION
# and LICENSE files.

#' pcir: Potential for Conflict Index in R
#'
#' The `pcir` package provides tools for calculating, comparing, and graphing
#' the Potential for Conflict Index (PCI), a descriptive statistical method
#' used in human dimensions research. The concepts of consensus and
#' disagreement/conflict hold relevance across various fields, including economics,
#' political science, psychology, sociology, and natural resources.
#'
#' @section pcir functions:
#' - \code{\link{counting}}: Create a count table with percentages, mean, and standard deviation.
#' - \code{\link{pci}}: Calculate the Potential for Conflict Index (PCI).
#' - \code{\link{bubble}}: Create a bubble plot to visualize PCI results.
#'
#' @docType package
#' @name pcir
NULL

# Define the content of the DESCRIPTION file
description_text <- "
Package: pcir
Title: Potential for Conflict Index in R
Version: 0.0.0.9000
Authors@R:
    person(\"Francesca\", \"Palmeira\", email = \"francesca@alumni.usp.br\",
    role = c(\"aut\", \"cre\"), comment = c(ORCID = \"0000-0002-7597-1157\"))
Description: Potential for Conflict Index in R - pcir, which is a descriptive
    statistical method used to enhance the understanding of outcomes in human
    dimensions research. The package equips users with tools required for
    calculating, comparing, and graphing the potential for conflict. The concepts
    of consensus and disagreement/conflict hold relevance across various fields,
    including economics, political science, psychology, sociology, and natural
    resources.
License: MIT + file LICENSE
Encoding: UTF-8
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.3.2
"

# Write the description to a DESCRIPTION file
writeLines(description_text, "DESCRIPTION")

# Define the content of the MIT License
license_text <- "
MIT License

Copyright (c) 2024 Francesca Palmeira

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the \"Software\"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"

# Write the license to a LICENSE file
writeLines(license_text, "LICENSE")

# Define the content of README.Rmd
readme_rmd_content <- "
---
title: 'pcir: Potential for Conflict Index in R'
output: github_document
---

[![R-CMD-check](https://github.com/fblpalmeira/pcir/main/R-CMD-check.yaml/badge.svg)](https://github.com/fblpalmeira/pcir)

`pcir` is an R package designed to help researchers and practitioners calculate,
compare, and visualize the Potential for Conflict Index (PCI). The PCI is a
descriptive statistical method used to enhance understanding of outcomes in
human dimensions research. It is relevant across fields such as economics,
political science, psychology, sociology, and natural resources.

## Features

- **`counting()`** summarize data by calculating counts, percentages, means, and
standard deviations.

- **`pci()`** compute the Potential for Conflict Index from summary data.

- **`bubble()`** visualize PCI results using a bubble plot.

## Installation

You can install the development version of `pcir` directly from GitHub:

```r
# Uncomment the line below if devtools is not installed
# install.packages(\"devtools\")
devtools::install_github(\"fblpalmeira/pcir\")
```

## License

This package is licensed under the MIT License. See the LICENSE file for more
details.

## Contact

For any questions or inquiries, please contact Francesca Palmeira at
francesca@alumni.usp.br.
"

#Write the README.Rmd file to the local repository
writeLines(readme_rmd_content, file.path(local_dir, "README.Rmd"))

#Add README.md to the Git stage
#repo_url <- git2r::repository(local_dir) git2r::add(repo_url, "README.Rmd")

#Commit the README.Rmd file
#git2r::commit(repo_url, "Add README.Rmd")

#Push the commit to the remote repository
#git2r::push(repo_url)

rmarkdown::render("README.Rmd")

# Initialize the website structure (only needed once)
pkgdown::init_site()

# Optional: Add the pkgdown configuration file (this step can be skipped if
# `pkgdown::init_site()` was used)
config_content <- "
url: https://fblpalmeira.github.io/pcir/
# Template settings
template:
  bootstrap: 5
  bootswatch: flatly

# Navbar settings
navbar:
  structure:
    left:
    - text: Reference
      href: reference
    - text: Articles
      href: articles
  right:
    - icon: fa-github
      href: https://github.com/fblpalmeira/pcir

# URL of the pkgdown website
#url: https://fblpalmeira.github.io/pcir/
"

# Write the configuration file
writeLines(config_content, file.path(local_dir, "_pkgdown.yml"))

# Build the site again to apply the config (if you added it)
pkgdown::build_site()

# Initialize git repository if not already initialized (skip if already done)
#repo <- repository()

# Stage all the changes, especially in the 'docs/' folder
#add(repo, "*")

# Commit the changes (including the docs folder)
#commit(repo, message = "Build and deploy pkgdown site to GitHub Pages")

# Push the changes to GitHub (you may need to authenticate if this is the first push)
# Define the remote origin URL (your GitHub repository)
#remote_add(repo, "origin", "https://github.com/fblpalmeira/pcir.git")

# Push to the GitHub repository (you may be prompted for credentials)
#push(repo, name = "origin", refspec = "refs/heads/master")

# Document, build, and install the package
devtools::document()
devtools::build()
devtools::install()
