
#' Calculate the Potential for Conflict Index (PCI)
#'
#' This function calculates the Potential for Conflict Index (PCI) based on the
#' counts provided. PCI is useful in understanding the level of consensus and
#' conflict in the data.
#'
#' @param df2 A data frame generated by the counting function, containing the
#' counts and related statistics.
#' @return A data frame with the calculated PCI values for each group.
#' @examples
#' df2 <- counting(df1)
#' pci_values <- pci(df2)
#' print(pci_values)
#' @export
pci <- function(df2) {
  df2$nu <- 1 * df2$Count -1
  df2$na <- 1 * df2$Count 1
  df2$xt <- df2$nu + df2$na
  df2$z <- 1 * df2$Total
  df2$PCI <-  (1 - (df2$na / df2$xt - df2$nu / df2$xt)) * df2$xt / df2$z
  df2 <- df2 %>%
    mutate_if(is.numeric, round, digits = 2)
  return(df2)
}

