
#' PCI Function
#'
#' @description Calculate the Potential for Conflict Index (PCI).
#' @param df2 A data frame generated by the `counting` function.
#' @return A data frame with the calculated PCI values for each group.
#' @examples
#' df2 <- counting(df1)
#' pci(df2)
#' @export
pci <- function(df2) {
  df2$nu <- 1 * df2$`Count -1`  # For Count -1 column
  df2$na <- 1 * df2$`Count 1`   # For Count 1 column
  df2$xt <- df2$nu + df2$na     # Sum of nu and na
  df2$z <- df2$Total            # Total count
  df2$PCI <- (1 - (df2$na / df2$xt - df2$nu / df2$xt)) * df2$xt / df2$z
  df2 <- df2 %>% mutate_if(is.numeric, round, digits = 2)
  return(df2)
}

